### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by nemesis2** [aelmahmoudy/cryptsetup-android#2]
Hello,

I'm attempting to build this on an Ubuntu 14.04.2 LTS virtual machine using android-ndk-r10d.  Everything builds except cryptsetup itself:

checking for dm_task_set_uuid in -ldevmapper... no
configure: error: Cannot link with static device-mapper library.
make: *** [cryptsetup/Makefile] Error 1

Building against:
cryptsetup-1.6.7.tar.gz
libgcrypt-1.6.3.tar.gz
libgpg-error-1.19.tar.gz
LVM2.2.02.111.tgz
popt-1.16.tar.gz
util-linux-2.25.2.tar.gz

Any thoughts or suggestions?

**Comment by aelmahmoudy** [comment]
Fixed in 837d29e3db0d648158c6a28577cd9b287cedb7bc

**Comment by aelmahmoudy** [comment]
You will need to rebuild lvm2

**Comment by nemesis2** [comment]
Thanks for the quick response!  That worked.  However, I'm not getting a static binary:

root@ubuntu:~/luks/cryptsetup/external# file sbin/*
sbin/blkdeactivate:      Bourne-Again shell script, ASCII text executable
sbin/cryptsetup:         ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), not stripped
sbin/cryptsetup.static:  ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), not stripped

I'm not quite sure what I'm doing wrong.  Based on the flags I should be getting a static binary.  When I compiled this back in 2011 I was getting:

cryptsetup:    ELF 32-bit LSB  executable, ARM, EABI4 version 1 (SYSV), statically linked, stripped

**Comment by aelmahmoudy** [comment]
Fixed. Seems that PIE flags were causing this problem !
